/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from 'gill';
import { STAKING_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const DELETE_STAKE_POOL_CONFIG_DISCRIMINATOR = new Uint8Array([2]);

export function getDeleteStakePoolConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    DELETE_STAKE_POOL_CONFIG_DISCRIMINATOR
  );
}

export type DeleteStakePoolConfigInstruction<
  TProgram extends string = typeof STAKING_PROGRAM_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      ...TRemainingAccounts,
    ]
  >;

export type DeleteStakePoolConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type DeleteStakePoolConfigInstructionDataArgs = {};

export function getDeleteStakePoolConfigInstructionDataEncoder(): FixedSizeEncoder<DeleteStakePoolConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 1)]]),
    (value) => ({
      ...value,
      discriminator: DELETE_STAKE_POOL_CONFIG_DISCRIMINATOR,
    })
  );
}

export function getDeleteStakePoolConfigInstructionDataDecoder(): FixedSizeDecoder<DeleteStakePoolConfigInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 1)],
  ]);
}

export function getDeleteStakePoolConfigInstructionDataCodec(): FixedSizeCodec<
  DeleteStakePoolConfigInstructionDataArgs,
  DeleteStakePoolConfigInstructionData
> {
  return combineCodec(
    getDeleteStakePoolConfigInstructionDataEncoder(),
    getDeleteStakePoolConfigInstructionDataDecoder()
  );
}

export type DeleteStakePoolConfigAsyncInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config?: Address<TAccountConfig>;
};

export async function getDeleteStakePoolConfigInstructionAsync<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof STAKING_PROGRAM_PROGRAM_ADDRESS,
>(
  input: DeleteStakePoolConfigAsyncInput<TAccountAuthority, TAccountConfig>,
  config?: { programAddress?: TProgramAddress }
): Promise<
  DeleteStakePoolConfigInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAKING_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103])),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.config),
    ],
    programAddress,
    data: getDeleteStakePoolConfigInstructionDataEncoder().encode({}),
  } as DeleteStakePoolConfigInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig
  >;

  return instruction;
}

export type DeleteStakePoolConfigInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config: Address<TAccountConfig>;
};

export function getDeleteStakePoolConfigInstruction<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof STAKING_PROGRAM_PROGRAM_ADDRESS,
>(
  input: DeleteStakePoolConfigInput<TAccountAuthority, TAccountConfig>,
  config?: { programAddress?: TProgramAddress }
): DeleteStakePoolConfigInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountConfig
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAKING_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.config),
    ],
    programAddress,
    data: getDeleteStakePoolConfigInstructionDataEncoder().encode({}),
  } as DeleteStakePoolConfigInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig
  >;

  return instruction;
}

export type ParsedDeleteStakePoolConfigInstruction<
  TProgram extends string = typeof STAKING_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    config: TAccountMetas[1];
  };
  data: DeleteStakePoolConfigInstructionData;
};

export function parseDeleteStakePoolConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedDeleteStakePoolConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      config: getNextAccount(),
    },
    data: getDeleteStakePoolConfigInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
