/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { STAKING_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_STAKE_POOL_CONFIG_DISCRIMINATOR = new Uint8Array([1]);

export function getUpdateStakePoolConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    UPDATE_STAKE_POOL_CONFIG_DISCRIMINATOR
  );
}

export type UpdateStakePoolConfigInstruction<
  TProgram extends string = typeof STAKING_PROGRAM_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateStakePoolConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  aprBps: bigint;
};

export type UpdateStakePoolConfigInstructionDataArgs = {
  aprBps: number | bigint;
};

export function getUpdateStakePoolConfigInstructionDataEncoder(): FixedSizeEncoder<UpdateStakePoolConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 1)],
      ['aprBps', getU128Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_STAKE_POOL_CONFIG_DISCRIMINATOR,
    })
  );
}

export function getUpdateStakePoolConfigInstructionDataDecoder(): FixedSizeDecoder<UpdateStakePoolConfigInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 1)],
    ['aprBps', getU128Decoder()],
  ]);
}

export function getUpdateStakePoolConfigInstructionDataCodec(): FixedSizeCodec<
  UpdateStakePoolConfigInstructionDataArgs,
  UpdateStakePoolConfigInstructionData
> {
  return combineCodec(
    getUpdateStakePoolConfigInstructionDataEncoder(),
    getUpdateStakePoolConfigInstructionDataDecoder()
  );
}

export type UpdateStakePoolConfigAsyncInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config?: Address<TAccountConfig>;
  aprBps: UpdateStakePoolConfigInstructionDataArgs['aprBps'];
};

export async function getUpdateStakePoolConfigInstructionAsync<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof STAKING_PROGRAM_PROGRAM_ADDRESS,
>(
  input: UpdateStakePoolConfigAsyncInput<TAccountAuthority, TAccountConfig>,
  config?: { programAddress?: TProgramAddress }
): Promise<
  UpdateStakePoolConfigInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAKING_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103])),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.config),
    ],
    programAddress,
    data: getUpdateStakePoolConfigInstructionDataEncoder().encode(
      args as UpdateStakePoolConfigInstructionDataArgs
    ),
  } as UpdateStakePoolConfigInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig
  >;

  return instruction;
}

export type UpdateStakePoolConfigInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config: Address<TAccountConfig>;
  aprBps: UpdateStakePoolConfigInstructionDataArgs['aprBps'];
};

export function getUpdateStakePoolConfigInstruction<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof STAKING_PROGRAM_PROGRAM_ADDRESS,
>(
  input: UpdateStakePoolConfigInput<TAccountAuthority, TAccountConfig>,
  config?: { programAddress?: TProgramAddress }
): UpdateStakePoolConfigInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountConfig
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAKING_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.config),
    ],
    programAddress,
    data: getUpdateStakePoolConfigInstructionDataEncoder().encode(
      args as UpdateStakePoolConfigInstructionDataArgs
    ),
  } as UpdateStakePoolConfigInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig
  >;

  return instruction;
}

export type ParsedUpdateStakePoolConfigInstruction<
  TProgram extends string = typeof STAKING_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    config: TAccountMetas[1];
  };
  data: UpdateStakePoolConfigInstructionData;
};

export function parseUpdateStakePoolConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateStakePoolConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      config: getNextAccount(),
    },
    data: getUpdateStakePoolConfigInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
