/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from 'gill';

export const STAKE_ACCOUNT_DISCRIMINATOR = new Uint8Array([3]);

export function getStakeAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    STAKE_ACCOUNT_DISCRIMINATOR
  );
}

export type StakeAccount = {
  discriminator: ReadonlyUint8Array;
  user: Address;
  stakePool: Address;
  stakedAmount: bigint;
  pendingRewards: bigint;
  interestIndexAtDeposit: bigint;
  bump: number;
};

export type StakeAccountArgs = {
  user: Address;
  stakePool: Address;
  stakedAmount: number | bigint;
  pendingRewards: number | bigint;
  interestIndexAtDeposit: number | bigint;
  bump: number;
};

export function getStakeAccountEncoder(): FixedSizeEncoder<StakeAccountArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 1)],
      ['user', getAddressEncoder()],
      ['stakePool', getAddressEncoder()],
      ['stakedAmount', getU64Encoder()],
      ['pendingRewards', getU64Encoder()],
      ['interestIndexAtDeposit', getU128Encoder()],
      ['bump', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: STAKE_ACCOUNT_DISCRIMINATOR })
  );
}

export function getStakeAccountDecoder(): FixedSizeDecoder<StakeAccount> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 1)],
    ['user', getAddressDecoder()],
    ['stakePool', getAddressDecoder()],
    ['stakedAmount', getU64Decoder()],
    ['pendingRewards', getU64Decoder()],
    ['interestIndexAtDeposit', getU128Decoder()],
    ['bump', getU8Decoder()],
  ]);
}

export function getStakeAccountCodec(): FixedSizeCodec<
  StakeAccountArgs,
  StakeAccount
> {
  return combineCodec(getStakeAccountEncoder(), getStakeAccountDecoder());
}

export function decodeStakeAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<StakeAccount, TAddress>;
export function decodeStakeAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<StakeAccount, TAddress>;
export function decodeStakeAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<StakeAccount, TAddress> | MaybeAccount<StakeAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getStakeAccountDecoder()
  );
}

export async function fetchStakeAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<StakeAccount, TAddress>> {
  const maybeAccount = await fetchMaybeStakeAccount(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeStakeAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<StakeAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeStakeAccount(maybeAccount);
}

export async function fetchAllStakeAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<StakeAccount>[]> {
  const maybeAccounts = await fetchAllMaybeStakeAccount(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeStakeAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<StakeAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeStakeAccount(maybeAccount));
}

export function getStakeAccountSize(): number {
  return 98;
}
